ShoppingWeb/Controllers/KhachhangController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShoppingWeb.Helpers;
using ShoppingWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingWeb.Controllers
{
    public class KhachhangController : Controller
    {
        private WEBBANHANGContext db = new WEBBANHANGContext();
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(string sdt, string pwd)
        {
            var account = db.Khachhangs.ToList();
            foreach (var item in account)
            {
                if (sdt != null && pwd != null && sdt.Equals(item.SdtKh) && pwd.Equals(item.MatKhau))
                {
                    HttpContext.Session.SetString("sdt", sdt);
                    return View("thanhcong");
                }
                else
                {
                    ViewBag.eror = "Sai tên tài khoản hoặc mật khẩu";
                }
            }
            return View("Index");
        }
        public IActionResult thanhcong()
        {
            return View();
        }
        public Khachhang getDetailKhachHang(int sdt)
        {
            var cus = db.Khachhangs.Find(sdt);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cus);
            return cus;
        }
    }
}

ShoppingWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Điện Thoại Rẻ</title>
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/js/script.js">

</head>
<body>
    <header>
        <div class="top_bar">
            <div class="container">
                <div class="row">
                    <div class="col d-flex flex-row">
                        <div class="top_bar_contact_item">
                            <i class="fas fa-mobile-alt"></i>
                            <a href="">+84 39 554 446</a>
                        </div>
                        <div class="top_bar_contact_item">
                            <i class="far fa-envelope"></i>
                            <a href="">thienvnps11984@fpt.edu.vn</a>
                        </div>
                        <div class="top_bar_content ml-auto">
                            <i class="far fa-user"></i>
                            <div class="top_bar_user">
                                <div>
                                    <a href="">Đăng ký</a>
                                </div>
                                <div>
                                    <a asp-controller="Khachhang" asp-action="index">Đăng nhập</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header_main_bar">
            <div class="container">
                <div class="row header_main">
                    <div class="logo col-sm-4"><a href="#">E-Commerce</a></div>
                    <div class="search_bar_container col-sm-4">
                        <div class="col-sm-4 search_bar_main">
                            <div class="search_name bar"><input type="search" class="search_bar" required="required" placeholder="Search for product..."></div>
                            <div class="search_icon bar">
                                <button class="search" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="wishlist_cart col-sm-4">
                        <div class="cart wc">
                            <div class="cart_icon">
                                <i class="fas fa-shopping-bag"></i>
                            </div>
                            <div class="cart_content"><a asp-controller="order" asp-action="index">Giỏ hàng</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bot_bar">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="menu_container">
                            <ul>
                                <li>
                                    <a class="cate category">Danh mục</a>
                                    <ul class="subs_menu1">
                                        <li>
                                            <a asp-controller="product" asp-action="index">Điện thoại</a>
                                            <ul class="subs_menu2">
                                                <li><a asp-controller="product" asp-action="iphone">Apple</a></li>
                                                <li><a asp-controller="product" asp-action="samsung">Samsung</a></li>
                                                <li><a asp-controller="product" asp-action="vsmart">Vsmart</a></li>
                                                <li><a asp-controller="product" asp-action="xiaomi">Xiaomi</a></li>
                                                <li><a asp-controller="product" asp-action="huawei">Huawei</a></li>
                                            </ul>
                                        </li>
                                        <li><a asp-controller="product" asp-action="tablet">Máy tính bảng</a></li>
                                        <li>
                                            <a asp-controller="product" asp-action="laptop">Laptop</a>
                                            
                                        </li>
                                        <li><a asp-controller="product" asp-action="macbook">Macbook</a></li>
                                    </ul>
                                </li>
                                <li class="justify_right"><a href="">Blog</a></li>
                                <li class="justify_right"><a href="">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="slide_carousel">
        <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="mask flex-center">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-7 col-12 order-md-1 order-2">
                                    <h4>
                                        Macbook Air M1 <br>
                                        2020
                                    </h4>
                                    <p>
                                        Apple MacBook Air M1 512GB 2020 <br>
                                        Chính Hãng Apple Việt Nam
                                    </p>
                                    <a href="#">BUY NOW</a>
                                </div>
                                <div class="col-md-5 col-12 order-md-2 order-1"><img src="~/image/Macbook Air 2020.png" class="mx-auto" alt="slide"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="mask flex-center">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-7 col-12 order-md-1 order-2">
                                    <h4>
                                        IPhone 12 Pro Max<br>
                                        256GB
                                    </h4>
                                    <p>
                                        iPhone 12 Pro 256GB Chính hãng (VN/A) bán tại Di Động Việt - Đại lý uỷ quyền chính thức của Apple tại Việt Nam<br>
                                        là phiên bản quốc tế 2 sim (Nano + Esim) chính hãng VN/A. Máy chưa Active + nguyên seal hộp, mới 100% (Fullbox)
                                    </p>
                                    <a href="#">BUY NOW</a>
                                </div>
                                <div class="col-md-5 col-12 order-md-2 order-1"><img src="~/image/IPhone 12 Pro Max.jpg" class="mx-auto" alt="slide"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="mask flex-center">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-7 col-12 order-md-1 order-2">
                                    <h4>
                                        SAMSUNG Galaxy<br>
                                        Z Fold 2 5G
                                    </h4>
                                    <p>
                                        Samsung Galaxy Z Fold 2 là tên gọi chính thức của điện thoại màn hình gập cao cấp nhất của Samsung. Với nhiều nâng cấp tiên phong về thiết kế, hiệu năng và camera<br>
                                        , hứa hẹn đây sẽ là một siêu phẩm thành công tiếp theo đến từ “ông trùm” sản xuất điện thoại lớn nhất thế giới.
                                    </p>
                                    <a asp-controller="detail" asp-action="buy">BUY NOW</a>
                                </div>
                                <div class="col-md-5 col-12 order-md-2 order-1"><img src="~/image/SAMSUNG Galaxy Z Fold 2 5G.jpg" class="mx-auto" alt="slide"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Company Name © 2018</p>
            </div>
        </footer>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ShoppingWeb/Views/Shared/_LayoutCate.cshtml
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@{
    var data = Context.Session.GetString("cart");

    int coutCart = 0;
    if (data == null)
    {
        coutCart = 0;
    }
    else
    {
        var data2 = Context.Session.GetString("cart");
        List<Chitietgiohang> dataCart = JsonConvert.DeserializeObject<List<Chitietgiohang>>(data2);
        foreach (var item in dataCart)
        {
            coutCart += item.SoLuong;
        }

    }

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Điện Thoại Rẻ</title>
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/js/script.js">

</head>
<body>
    <header>
        <div class="top_bar">
            <div class="container">
                <div class="row">
                    <div class="col d-flex flex-row">
                        <div class="top_bar_contact_item">
                            <i class="fas fa-mobile-alt"></i>
                            <a href="">+84 39 554 446</a>
                        </div>
                        <div class="top_bar_contact_item">
                            <i class="far fa-envelope"></i>
                            <a href="">thienvnps11984@fpt.edu.vn</a>
                        </div>
                        <div class="top_bar_content ml-auto">
                            <i class="far fa-user"></i>
                            <div class="top_bar_user">
                                <div>
                                    <a href="">Đăng ký</a>
                                </div>
                                <div>
                                    <a asp-controller="khachhang" asp-action="index">Đăng nhập</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header_main_bar">
            <div class="container">
                <div class="row header_main">
                    <div class="logo col-sm-4"><a href="#">E-Commerce</a></div>
                    <div class="search_bar_container col-sm-4">
                        <div class="col-sm-4 search_bar_main">
                            <div class="search_name bar"><input type="search" class="search_bar" required="required" placeholder="Search for product..."></div>
                            <div class="search_icon bar">
                                <button class="search" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="wishlist_cart col-sm-4">
                        
                        <div class="cart wc">
                            <div class="cart_icon">
                                <i class="fas fa-shopping-bag"></i>
                            </div>
                            <div class="cart_content">
                                <a asp-controller="order" asp-action="index">Giỏ hàng</a>
                                @coutCart
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bot_bar">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="menu_container">
                            <ul>
                                <li>
                                    <a class="cate category">Danh mục</a>
                                    <ul class="subs_menu1">
                                        <li>
                                            <a asp-controller="product" asp-action="index">Điện thoại</a>
                                            <ul class="subs_menu2">
                                                <li><a asp-controller="product" asp-action="iphone">Apple</a></li>
                                                <li><a asp-controller="product" asp-action="samsung">Samsung</a></li>
                                                <li><a asp-controller="product" asp-action="vsmart">Vsmart</a></li>
                                                <li><a asp-controller="product" asp-action="xiaomi">Xiaomi</a></li>
                                                <li><a asp-controller="product" asp-action="huawei">Huawei</a></li>
                                            </ul>
                                        </li>
                                        <li><a asp-controller="product" asp-action="tablet">Máy tính bảng</a></li>
                                        <li>
                                            <a asp-controller="product" asp-action="laptop">Laptop</a>
                                        </li>
                                        <li><a asp-controller="product" asp-action="macbook">Macbook</a></li>
                                    </ul>
                                </li>
                                <li class="justify_right"><a href="">Blog</a></li>
                                <li class="justify_right"><a href="">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--
    <div class="slide_carousel">
        <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="mask flex-center">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-7 col-12 order-md-1 order-2">
                                    <h4>
                                        Present your <br>
                                        awesome product
                                    </h4>
                                    <p>
                                        Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum <br>
                                        necessitatibus praesentium voluptatum deleniti atque corrupti.
                                    </p>
                                    <a href="#">BUY NOW</a>
                                </div>
                                <div class="col-md-5 col-12 order-md-2 order-1"><img src="https://i.imgur.com/NKvkfTT.png" class="mx-auto" alt="slide"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="mask flex-center">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-7 col-12 order-md-1 order-2">
                                    <h4>
                                        Present your <br>
                                        awesome product
                                    </h4>
                                    <p>
                                        Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum <br>
                                        necessitatibus praesentium voluptatum deleniti atque corrupti.
                                    </p>
                                    <a href="#">BUY NOW</a>
                                </div>
                                <div class="col-md-5 col-12 order-md-2 order-1"><img src="https://i.imgur.com/duWgXRs.png" class="mx-auto" alt="slide"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="mask flex-center">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-7 col-12 order-md-1 order-2">
                                    <h4>
                                        Present your <br>
                                        awesome product
                                    </h4>
                                    <p>
                                        Lorem ipsum dolor sit amet. Reprehenderit, qui blanditiis quidem rerum <br>
                                        necessitatibus praesentium voluptatum deleniti atque corrupti.
                                    </p>
                                    <a href="#">BUY NOW</a>
                                </div>
                                <div class="col-md-5 col-12 order-md-2 order-1"><img src="https://i.imgur.com/DGkR4OQ.png" class="mx-auto" alt="slide"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    -->
    <div class="container">
        @RenderBody()
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Company Name © 2018</p>
            </div>
        </footer>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}